language: c
matrix:
  include:
    - os: osx
      env: TEST_SUITE=testinstall
      compiler: clang
    - os: linux
      env: TEST_SUITE=testinstall
      compiler: gcc
    - os: linux
      env: TEST_SUITE=testbugfix
      compiler: gcc
    - os: linux
      env: TEST_SUITE=makemanuals
      compiler: gcc

# Change this to your needs
addons:
  apt_packages:
  - libgmp3-dev
  - texlive-latex-base
  - texlive-latex-recommended
  - texlive-latex-extra
  - texlive-extra-utils
  - texlive-fonts-recommended
  - texlive-fonts-extra
script:
  - ./configure --with-gmp=system
  - make
  - make bootstrap-pkg-full
  - if [ $TEST_SUITE = 'makemanuals' ]; then if [ $TRAVIS_OS_NAME = 'linux' ]; then make manuals ; cat doc/*/make_manuals.out ; if [ `cat doc/*/make_manuals.out | grep -c "manual.lab written"` != '3' ]; then echo "Build failed"; exit 1; fi; fi; fi
  - if [ $TEST_SUITE != 'makemanuals' ]; then echo "Read(\"tst/${TEST_SUITE}.g\"); quit;" | sh bin/gap.sh | tee testlog.txt | grep --colour=always -E "########> Diff|$"; cat testlog.txt | tail -n 2 | grep "total"; ( ! grep "########> Diff" testlog.txt ); fi
