## This file is automatically generated by AutoDoc.
## Changes will be discarded by the next call of the AutoDoc method.


LoadPackage( "MonoidalCategories" );

LoadPackage( "MatricesForHomalg" );

LoadPackage( "GaussForHomalg" );

AUTODOC_file_scan_list := [ "../PackageInfo.g", "../examples/BasicTests.g", "../examples/VectorSpacesMonoidalCategory.gi", "../gap/AdditiveMonoidalCategories.gd", "../gap/AdditiveMonoidalCategories.gi", "../gap/AdditiveMonoidalCategoriesDerivedMethods.gi", "../gap/AdditiveMonoidalCategoriesMethodRecord.gi", "../gap/BraidedMonoidalCategories.gd", "../gap/BraidedMonoidalCategories.gi", "../gap/BraidedMonoidalCategoriesDerivedMethods.gi", "../gap/BraidedMonoidalCategoriesDoc.gd", "../gap/BraidedMonoidalCategoriesMethodRecord.gi", "../gap/ClosedMonoidalCategories.gd", "../gap/ClosedMonoidalCategories.gi", "../gap/ClosedMonoidalCategoriesDerivedMethods.gi", "../gap/ClosedMonoidalCategoriesDoc.gd", "../gap/ClosedMonoidalCategoriesMethodRecord.gi", "../gap/MonoidalCategories.gd", "../gap/MonoidalCategories.gi", "../gap/MonoidalCategoriesDerivedMethods.gi", "../gap/MonoidalCategoriesDoc.gd", "../gap/MonoidalCategoriesMethodRecord.gi", "../gap/MonoidalCategoriesTensorProductAndUnitMethodRecord.gi", "../gap/MonoidalCategoriesTensorProductOnObjectsAndUnitObject.gd", "../gap/MonoidalCategoriesTensorProductOnObjectsAndUnitObject.gi", "../gap/RigidSymmetricClosedMonoidalCategories.gd", "../gap/RigidSymmetricClosedMonoidalCategories.gi", "../gap/RigidSymmetricClosedMonoidalCategoriesDerivedMethods.gi", "../gap/RigidSymmetricClosedMonoidalCategoriesDoc.gd", "../gap/RigidSymmetricClosedMonoidalCategoriesMethodRecord.gi", "../gap/SymmetricClosedMonoidalCategoriesDerivedMethods.gi", "../gap/SymmetricClosedMonoidalCategoriesDoc.gd", "../gap/SymmetricMonoidalCategoriesDerivedMethods.gi", "../gap/SymmetricMonoidalCategoriesDoc.gd", "../init.g", "../makedoc.g", "../read.g", "/home/gap/.gap/pkg/CAP_project/tmp/MonoidalCategories-2020.10-01/doc/_Chunks.xml" ];

LoadPackage( "GAPDoc" );

example_tree := ExtractExamples( Directory("./doc/"), "MonoidalCategories.xml", AUTODOC_file_scan_list, 500 );

RunExamples( example_tree, rec( compareFunction := "uptowhitespace" ) );

QUIT;
